name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t harshan536/node-js-1 . 

      - name: Push Docker image
        run: docker push harshan536/node-js-1

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: docker pull harshan536/node-js-1
      - name: Remove Exiting images
        run: docker rm reverent_feistel
      - name: Run docker container
        run: docker run -d -p 3001:3000 --name node-app-container harshan536/node-js-1

        

